version: '3.8' # or the appropriate version for your setup

services:
  mariadb:
    image: docker.io/library/mariadb:11.4.2
    container_name: mariadb
    env_file:
      - .env

    ports:
      - "3307:3306"

    networks:
      - mynet
    volumes:
      - ./backup/database_${NODE_ENV}:/var/lib/mysql
      - ./mariadb/initdb:/docker-entrypoint-initdb.d
    

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    container_name: backend

    env_file:
      - .env

    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - mynet
    volumes:
      - ./backup/backend/images:/app/uploads
      - ./backend/:/app
      - /app/node_modules
      - ./backup/backend/logs:/app/data/logs

    command: npm run start:dev

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: ./dockerfile.dev

    container_name: frontend

    ports:
      - "5173:5173"

    networks:
      - mynet
    volumes:
      - ./frontend:/app # Mounts the current directory to /app in the container
      - /app/node_modules # Prevents conflicts with node_modules on the host
    environment:
      - CHOKIDAR_USEPOLLING=true # Enables file change detection in Docker for Windows/Mac

networks:
  # The presence of these objects is sufficient to define them
  mynet: {}


# volumes:
#   myvol: